/* ==========================================================================
   MKSIN.C - Lesson 5. The table the game needs, written by a program.

       wcl -0 -ml -bcl=dos MKSIN.C
       MKSIN > SINT.INC

   This is the first program in the series that is NOT the game. It never
   runs on the 8086 - it runs once, on whatever machine you are sitting at,
   and what it produces is assembly source. That is the whole arrangement
   this repository is built on: today's tools prepare the data, and the 8086
   is the runtime, never the toolchain.

   Look at what it uses. sin(). A double. Floating point, which the machine
   the lesson is about does not have and will never need - because none of it
   survives the printf. What comes out the other end is sixty-five integers.

   WHY 64 STEPS AND WHY 256. A quarter circle is cut into 64, so a whole
   circle is 256 - which fits in a byte, and an angle wraps with AND 255
   instead of a division. And the sine is kept as sin*256, so 1.0 is 256 and
   the fraction survives in an integer. Both numbers are powers of two, and
   that is the only reason either of them was chosen.

   Owlos - legacy software modernization - https://owlos.sk
   ========================================================================== */
#include <stdio.h>
#include <math.h>

#define QUARTER 64      /* steps in a quarter circle: a whole one is 256 */
#define SCALE   256     /* sin * 256, so 1.0 comes out as 256            */
#define PERLINE 13      /* 5 lines of 13 is exactly 65                   */

int main(void)
{
    int    i;
    int    v;
    double a;

    printf("; SINT.INC - GENERATED by MKSIN.EXE. Do not edit by hand.\n");
    printf("; sin(a) * %d, for a from 0 to 90 degrees in %d steps.\n",
           SCALE, QUARTER);
    printf("; A whole circle is %d of these steps, so an angle wraps with\n",
           QUARTER * 4);
    printf("; AND %d and never needs a division.\n", QUARTER * 4 - 1);

    for (i = 0; i <= QUARTER; i++)
    {
        a = (double) i * (3.14159265358979 / 2.0) / (double) QUARTER;

        /* floor(x + 0.5), not a cast: a cast truncates, and truncating a
           sine table leaves it consistently short. The rounding is the
           only place this program can be wrong, and it is worth being
           right in - see the note in the lesson about the value at 26. */
        v = (int) floor(sin(a) * (double) SCALE + 0.5);

        if (i % PERLINE == 0)
            printf("\n%-8sdw %d", i == 0 ? "SINT" : "", v);
        else
            printf(",%d", v);
    }
    printf("\n");
    return 0;
}
