# mkpanel.py - convert the cockpit artwork into game resources:
#   res/panel1.bmp - the ART: what the player sees (white = viewport)
#   res/panel2.bmp - the MARKUP: same image with flat colour rectangles
#                    telling the game where the instruments live
# Outputs:
#   PANELIMG.INC - 64000 palette-index bytes, resource id 2 in CITY.DAT.
#                  255 = transparent, panel colours at palette 31..93.
#   PALPNL.INC   - 63 VGA DAC triplets appended to PALDAY/PALNITE.
# Markup colours (MS Paint / Photoshop defaults):
#   red   (237,28,36)   radar MFD      blue (0,162,232)  ADI MFD
#   green (34,177,76)   map MFD        cyan (153,217,234) text/lamp areas
# All marked zones are flattened to a dark glass colour in the art so the
# instruments draw on a clean background. Zone coordinates are printed -
# they are hardcoded in HUD.INC (PANELBMP), update it if the layout moves.
# Run from the repo root:  python res\mkpanel.py
import os
from PIL import Image

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
art = Image.open(os.path.join(root, 'res', 'panel1.bmp')).convert('RGB')
mrk = Image.open(os.path.join(root, 'res', 'panel2.bmp')).convert('RGB')
assert art.size == (320, 200) and mrk.size == (320, 200)
w, h = art.size
apx, mpx = art.load(), mrk.load()

def near(c, t, tol=30):
    return all(abs(a - b) < tol for a, b in zip(c, t))

def blobs(target, tol=30, minpx=15):
    seen = bytearray(w * h)
    out = []
    for y0 in range(h):
        for x0 in range(w):
            if seen[y0 * w + x0] or not near(mpx[x0, y0], target, tol):
                continue
            stack = [(x0, y0)]
            seen[y0 * w + x0] = 1
            xs, ys, n = [], [], 0
            while stack:
                x, y = stack.pop()
                xs.append(x); ys.append(y); n += 1
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    nx, ny = x + dx, y + dy
                    if 0 <= nx < w and 0 <= ny < h and not seen[ny * w + nx] \
                       and near(mpx[nx, ny], target, tol):
                        seen[ny * w + nx] = 1
                        stack.append((nx, ny))
            if n >= minpx:
                out.append((n, min(xs), min(ys), max(xs), max(ys)))
    out.sort(reverse=True)
    return out

SCREEN_DARK = (10, 14, 20)
# colour, max blobs to take, flatten to dark glass (False = the artwork
# already draws the background; the game only overlays content there)
MARKERS = {
    'RADAR (red)':  ((237, 28, 36),   1,  True),
    'ADI (blue)':   ((0, 162, 232),   1,  True),
    'MAP (green)':  ((34, 177, 76),   1,  True),
    'TEXT (cyan)':  ((153, 217, 234), 99, False),
}
for name, (col, take, paint) in MARKERS.items():
    for n, x0, y0, x1, y1 in blobs(col)[:take]:
        print(f'{name}: x {x0}..{x1}  y {y0}..{y1}  ({x1-x0+1}x{y1-y0+1})')
        if not paint:
            continue
        for y in range(max(0, y0 - 1), min(h, y1 + 2)):
            for x in range(max(0, x0 - 1), min(w, x1 + 2)):
                apx[x, y] = SCREEN_DARK

# transparency from the ART's near-white pixels
transparent = bytearray(w * h)
for y in range(h):
    for x in range(w):
        r, g, b = apx[x, y]
        if r >= 240 and g >= 240 and b >= 240:
            transparent[y * w + x] = 1
print(f'transparent pixels: {sum(transparent)}')

# (defringe removed: the artist cleans the glass edges in Photoshop -
# dark frame layer + hard white fill with anti-aliasing off)

q = art.quantize(colors=63, dither=Image.Dither.FLOYDSTEINBERG)
qpx = q.load()
pal = q.getpalette()[:63 * 3]

data = bytearray(w * h)
for y in range(h):
    for x in range(w):
        i = y * w + x
        data[i] = 255 if transparent[i] else 31 + qpx[x, y]

spans = 0
prev = True
for v in data:
    t = (v == 255)
    if prev and not t:
        spans += 1
    prev = t
print(f'blit spans: {spans} (loader cap 1599)')
assert spans <= 1599, 'too many spans - simplify the transparent area'

with open(os.path.join(root, 'PANELIMG.INC'), 'w', encoding='ascii') as f:
    f.write('; PANELIMG.INC - generated by res\\mkpanel.py from res\\panel1.bmp\n')
    f.write('; 320x200 palette indexes, 255 = transparent. DO NOT EDIT BY HAND.\n')
    for i in range(0, len(data), 20):
        f.write('        db ' + ','.join(str(b) for b in data[i:i + 20]) + '\n')
print('wrote PANELIMG.INC')

with open(os.path.join(root, 'PALPNL.INC'), 'w', encoding='ascii') as f:
    f.write('; PALPNL.INC - generated by res\\mkpanel.py, 63 panel colours\n')
    f.write('; (VGA DAC 0..63), palette indexes 31..93. DO NOT EDIT BY HAND.\n')
    for i in range(63):
        r, g, b = pal[i * 3] >> 2, pal[i * 3 + 1] >> 2, pal[i * 3 + 2] >> 2
        f.write(f'        db {r},{g},{b}          ;{31 + i}\n')
print('wrote PALPNL.INC')
