// ============================================================================
//  Obj2Inc - Wavefront OBJ -> WIRE CITY engine tables, as a TASM include.
//  The C# member of the model pipeline (the tooling contract: new tools
//  are C#). Mirrors OBJ2DAT.COM's integer arithmetic exactly: the
//  fraction is truncated to 4 digits and scaled as
//  (frac * scale + den / 2) / den, rounding half away from zero.
//
//      dotnet run --project TOOLS\Obj2Inc -- model.obj -o MODEL.INC [-n MDL] [-s 4]
//
//  Output:  <N>NV equ / <N>NF equ / <N>VT label word / <N>FC label byte
//  Axis map (Blender OBJ default: -Z forward, Y up):
//      engine X = obj X,  engine Y = obj Y,  engine Z = -obj Z
//  Quads pass through; triangles fold the last corner; 5+ corners are
//  an error. Materials PALnn carry the palette index; others warn and
//  fall back to 20.
// ============================================================================
using System.Text;
using System.Text.RegularExpressions;

int scale = 4;
string objPath = null, outPath = null, prefix = "MDL";
for (int i = 0; i < args.Length; i++)
{
    switch (args[i])
    {
        case "-o": outPath = args[++i]; break;
        case "-n": prefix = args[++i]; break;
        case "-s": scale = int.Parse(args[++i]); break;
        default: objPath = args[i]; break;
    }
}
if (objPath == null || outPath == null)
{
    Console.Error.WriteLine("usage: Obj2Inc model.obj -o MODEL.INC [-n MDL] [-s 4]");
    return 1;
}

// scale a decimal literal exactly as OBJ2DAT.COM does
int Snum(string s)
{
    bool neg = s.StartsWith("-");
    if (neg || s.StartsWith("+")) s = s[1..];
    if (s.Contains('e') || s.Contains('E'))
        throw new Exception($"exponent notation unsupported: {s}");
    var parts = s.Split('.', 2);
    string ip = parts[0], fp = parts.Length > 1 ? parts[1] : "";
    if (fp.Length > 4) fp = fp[..4];
    long v = (ip.Length > 0 ? long.Parse(ip) : 0) * scale;
    if (fp.Length > 0)
    {
        long den = 1; for (int k = 0; k < fp.Length; k++) den *= 10;
        v += (long.Parse(fp) * scale + den / 2) / den;
    }
    return (int)(neg ? -v : v);
}

var verts = new List<(int x, int y, int z)>();
var faces = new List<(int[] idx, int col)>();
int colour = 20;
foreach (var line in File.ReadLines(objPath))
{
    var t = line.Split((char[])null, StringSplitOptions.RemoveEmptyEntries);
    if (t.Length == 0) continue;
    if (t[0] == "v")
    {
        int x = Snum(t[1]), y = Snum(t[2]), z = Snum(t[3]);
        verts.Add((x, y, -z));                  // obj -Z forward -> engine +Z
    }
    else if (t[0] == "usemtl")
    {
        var m = Regex.Match(t[1], @"^PAL(\d+)$");
        if (m.Success) colour = int.Parse(m.Groups[1].Value);
        else { Console.Error.WriteLine($"warning: unknown material '{t[1]}', using PAL20"); colour = 20; }
    }
    else if (t[0] == "f")
    {
        var idx = t.Skip(1).Select(w => int.Parse(w.Split('/')[0]) - 1).ToList();
        if (idx.Count == 3) idx.Add(idx[2]);    // triangle = folded quad
        if (idx.Count != 4)
        { Console.Error.WriteLine($"error: {idx.Count}-gon found - subdivide it in Blender"); return 1; }
        faces.Add((idx.ToArray(), colour));
    }
}
if (verts.Count > 255)
{ Console.Error.WriteLine($"error: {verts.Count} verts - face indices are bytes, max 255"); return 1; }
foreach (var v in verts)
    if (Math.Abs(v.x) > 32000 || Math.Abs(v.y) > 32000 || Math.Abs(v.z) > 32000)
    { Console.Error.WriteLine($"error: vertex ({v.x},{v.y},{v.z}) overflows a word - lower -s"); return 1; }

var n = prefix.ToUpperInvariant();
var sb = new StringBuilder();
sb.Append($"; generated by Obj2Inc from {objPath.Replace('\\', '/')} - do not edit by hand\r\n");
sb.Append($"{n}NV equ {verts.Count}\r\n");
sb.Append($"{n}NF equ {faces.Count}\r\n");
sb.Append($"{n}VT label word\r\n");
foreach (var (x, y, z) in verts)
    sb.Append($"        dw {x,6},{y,6},{z,6}\r\n");
sb.Append($"{n}FC label byte\r\n");
foreach (var (idx, col) in faces)
    sb.Append($"        db {idx[0],3},{idx[1],3},{idx[2],3},{idx[3],3}, {col,3}\r\n");
File.WriteAllText(outPath, sb.ToString());
Console.WriteLine($"{verts.Count} verts, {faces.Count} faces -> {outPath}");
return 0;
