// SinTab - mint the sine table an 8086 lesson includes.
//
//   dotnet run --project TOOLS\SinTab -- LESSONS\L10\SINTAB.INC
//
// 256 cells, the whole circle in one byte: round(127 * sin(i*2pi/256)),
// signed -127..127, sixteen to a row, under the label SINTAB. The machine
// has no sine - a table has, and this is where the table comes from. The
// games' hsin/hcos were minted the same way, at their own scale.
//
// C#, per the project's tooling contract. Output is committed: a plain
// build never needs this to have run.

if (args.Length < 1)
{
    Console.Error.WriteLine("usage: SinTab <output.INC>");
    return 1;
}

var w = new StringWriter();
w.NewLine = "\r\n";                       // a DOS file, CRLF or Volkov weeps
w.WriteLine("; ============================================================================");
w.WriteLine(";  SINTAB.INC - the sine, minted once: 256 cells, the whole circle in one");
w.WriteLine(";  byte. Each cell is round(127 * sin(i * 2*pi / 256)), a signed byte:");
w.WriteLine(";  -127..127, so a length multiplied through IMUL and shifted right seven");
w.WriteLine(";  places (/128) comes out in pixels. cos(a) is this same table read at");
w.WriteLine(";  a + 64: a quarter of 256 is a quarter of the circle.");
w.WriteLine(";");
w.WriteLine(";  GENERATED by TOOLS\\SinTab (dotnet run --project TOOLS\\SinTab -- <path>).");
w.WriteLine(";  Nobody typed these numbers, and nobody in 1988 typed theirs either -");
w.WriteLine(";  the games' hsin and hcos are this table's grown-up kin.");
w.WriteLine("; ============================================================================");
w.WriteLine("SINTAB:");
for (int row = 0; row < 16; row++)
{
    var cells = new List<string>();
    for (int i = 0; i < 16; i++)
    {
        int n = row * 16 + i;
        int v = (int)Math.Round(127.0 * Math.Sin(n * 2.0 * Math.PI / 256.0));
        cells.Add(v.ToString());
    }
    w.WriteLine("        db   " + string.Join(",", cells));
}

File.WriteAllText(args[0], w.ToString());
Console.WriteLine($"minted {args[0]}: 256 cells, -127..127");
return 0;
