<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Cab2Dat</AssemblyName>
    <RootNamespace>Cab2Dat</RootNamespace>
  </PropertyGroup>
</Project>
