// RecipTab - mint the reciprocal table a perspective lesson includes.
//
//   dotnet run --project TOOLS\RecipTab -- LESSONS\L15\RECIP.INC [d] [near]
//
// 256 cells, one WORD each: d/z in 8.8 fixed point - round(d * 256 / z) -
// indexed by the depth z as a byte, under the label RECIP. The machine has
// no divide worth paying for and one that can trap; a table has neither
// fault. x*d/z becomes a lookup, one IMUL and a shift by eight - the same
// three moves the sine table bought us in lesson 10.
//
// THE TABLE HAS NO ROW ZERO. Rows 0..near-1 hold 0, on purpose: a depth
// that close has no honest reciprocal (it would overflow the word, and
// the divide it replaces would overflow the register), so a vertex that
// reads there collapses to the centre of the screen instead of crashing
// the machine. That is the difference between the table and DIV, and the
// NEAR PLANE is the program's promise never to ask. Row 255 is the far
// plane: a depth past a byte has no address at all.
//
// C#, per the project's tooling contract. Output is committed: a plain
// build never needs this to have run.

if (args.Length < 1)
{
    Console.Error.WriteLine("usage: RecipTab <output.INC> [d=100] [near=50]");
    return 1;
}
int d    = args.Length > 1 ? int.Parse(args[1]) : 100;
int near = args.Length > 2 ? int.Parse(args[2]) : 50;

var w = new StringWriter();
w.NewLine = "\r\n";                       // a DOS file, CRLF or Volkov weeps
w.WriteLine("; ============================================================================");
w.WriteLine(";  RECIP.INC - the divide, minted once: 256 cells, one WORD each, holding");
w.WriteLine($";  d/z in 8.8 fixed point with d = {d} - that is round({d} * 256 / z), read");
w.WriteLine(";  at row z. Multiply a coordinate by a cell through IMUL and shift the");
w.WriteLine(";  product right eight places (/256), and out comes x*d/z in pixels with");
w.WriteLine(";  no DIV anywhere: a lookup, a multiply, a shift - the sine table's three");
w.WriteLine(";  moves, aimed at division.");
w.WriteLine(";");
w.WriteLine($";  THE TABLE HAS NO ROW ZERO. Rows 0..{near - 1} hold 0, on purpose. A depth");
w.WriteLine(";  that close has no honest reciprocal - the divide this replaces would");
w.WriteLine(";  overflow its register and fire INT 0 - so a vertex that reads here");
w.WriteLine(";  collapses to the centre of the screen instead of crashing the machine.");
w.WriteLine($";  The NEAR PLANE, at {near}, is the program's promise never to ask. Row 255");
w.WriteLine(";  is the FAR plane: a depth past a byte has no address at all.");
w.WriteLine(";");
w.WriteLine(";  GENERATED by TOOLS\\RecipTab (dotnet run --project TOOLS\\RecipTab -- <path>).");
w.WriteLine(";  Nobody typed these numbers. Every DOS engine that drew a corridor had a");
w.WriteLine(";  table like this one, and none of them typed theirs either.");
w.WriteLine("; ============================================================================");
w.WriteLine("RECIP:");
for (int row = 0; row < 32; row++)
{
    var cells = new List<string>();
    for (int i = 0; i < 8; i++)
    {
        int z = row * 8 + i;
        int v = z < near ? 0 : (int)Math.Round(d * 256.0 / z);
        if (v > 32767) v = 32767;
        cells.Add(v.ToString());
    }
    w.WriteLine("        dw   " + string.Join(",", cells));
}

File.WriteAllText(args[0], w.ToString());
Console.WriteLine($"minted {args[0]}: 256 words, d={d}, near={near}, row {near} = {Math.Round(d * 256.0 / near)}, row 255 = {Math.Round(d * 256.0 / 255)}");
return 0;
